#!/bin/sh

DEPENDS="dashbinsh zsh nvim scrot xclip lf picom-git fast-syntax-highlighting zsh-autosuggestions pulseaudio xorg xorg-xinit unclutter brave-bin mpv sxiv zathura-pdf-mupdf"

DIR=$(pwd)

# Install dotfiles
cp -rf "$DIR"/.config "$HOME"
cp -rf "$DIR"/.local "$HOME"

ln -sf "$HOME"/.config/shell/profile "$HOME"/.zprofile
ln -sf "$HOME"/.config/x11/xinitrc "$HOME"/.xinitrc

# Refresh package databases
pacman -Sy 2>/dev/null

# Refresh keyring
pacman -Q artix-keyring >/dev/null 2>&1 && pacman --noconfirm -S artix-keyring >/dev/null 2>&1
pacman --noconfirm -S archlinux-keyring >/dev/null 2>&1

# Install git and base-devel with pacman
pacman --noconfirm --needed -S base-devel git 2>/dev/null

# Use all cores for compilation.
sed -i "s/-j2/-j$(nproc)/;s/^#MAKEFLAGS/MAKEFLAGS/" /etc/makepkg.conf

# Install paru (AUR helper)
cd /tmp
git clone https://aur.archlinux.org/paru.git 2>/dev/null
cd paru
makepkg --noconfirm --needed --clean -si 2>/dev/null
rm -rf ../paru 2>/dev/null

# Install the rest of dependencies
paru --noconfirm --needed -S "$DEPENDS" 2>/dev/null

# Remove beep
rmmod pcspkr
echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf

# Make pacman look better
grep -q "^Color" /etc/pacman.conf || sed -i "s/^#Color$/Color/" /etc/pacman.conf
grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf

# Make zsh the default shell
chsh -s /bin/zsh "$name" >/dev/null 2>&1

# Generate dbus UUID
dbus-uuidgen > /var/lib/dbus/machine-id

# Tap to click
[ ! -f /etc/X11/xorg.conf.d/40-libinput.conf ] && printf 'Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
	Option "Tapping" "on"
EndSection' > /etc/X11/xorg.conf.d/40-libinput.conf

# Change trackpoint settings
[ ! -f /etc/udev/rules.d/10-trackpoint.rules ] && printf 'ACTION=="add", SUBSYSTEM=="input", ATTR{name}=="TPPS/2 IBM TrackPoint", ATTR{device/drift_time}="25", ATTR{device/sensitivity}="200"' > /etc/udev/rules.d/10-trackpoint.rules

# Fix fluidsynth/pulseaudio issue.
grep -q "OTHER_OPTS='-a pulseaudio -m alsa_seq -r 48000'" /etc/conf.d/fluidsynth ||
	echo "OTHER_OPTS='-a pulseaudio -m alsa_seq -r 48000'" >> /etc/conf.d/fluidsynth

# Start/restart PulseAudio.
killall pulseaudio; sudo -u "$name" pulseaudio --start
