#!/bin/sh

xwallpaper --center $WALLPAPER &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources 2>/dev/null
dwmblocks &
dunst &
picom --experimental-backends &
xautolock -time 5 -locker slock
xset r rate 300 50 &
unclutter &

pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
