#!/bin/sh

locker &
remaps &
setbg &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources
mpd &
dwmblocks &
dunst &
picom --experimental-backends &
unclutter &

pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
